/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Assignment1Record extends org.jooq.impl.TableRecordImpl<tech.codingclub.helix.tables.records.Assignment1Record> implements org.jooq.Record5<java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.lang.String> {

	private static final long serialVersionUID = 1669758784;

	/**
	 * Setter for <code>public.assignment1.Eid</code>.
	 */
	public void setEid(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.assignment1.Eid</code>.
	 */
	public java.lang.Long getEid() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.assignment1.EName</code>.
	 */
	public void setEname(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.assignment1.EName</code>.
	 */
	public java.lang.String getEname() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.assignment1.DOJ</code>.
	 */
	public void setDoj(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.assignment1.DOJ</code>.
	 */
	public java.lang.String getDoj() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.assignment1.YOE</code>.
	 */
	public void setYoe(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.assignment1.YOE</code>.
	 */
	public java.lang.Long getYoe() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>public.assignment1.Designation</code>.
	 */
	public void setDesignation(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.assignment1.Designation</code>.
	 */
	public java.lang.String getDesignation() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return tech.codingclub.helix.tables.Assignment1.ASSIGNMENT1.EID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return tech.codingclub.helix.tables.Assignment1.ASSIGNMENT1.ENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return tech.codingclub.helix.tables.Assignment1.ASSIGNMENT1.DOJ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return tech.codingclub.helix.tables.Assignment1.ASSIGNMENT1.YOE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return tech.codingclub.helix.tables.Assignment1.ASSIGNMENT1.DESIGNATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getEid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getEname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDoj();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getYoe();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getDesignation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Assignment1Record value1(java.lang.Long value) {
		setEid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Assignment1Record value2(java.lang.String value) {
		setEname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Assignment1Record value3(java.lang.String value) {
		setDoj(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Assignment1Record value4(java.lang.Long value) {
		setYoe(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Assignment1Record value5(java.lang.String value) {
		setDesignation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Assignment1Record values(java.lang.Long value1, java.lang.String value2, java.lang.String value3, java.lang.Long value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached Assignment1Record
	 */
	public Assignment1Record() {
		super(tech.codingclub.helix.tables.Assignment1.ASSIGNMENT1);
	}

	/**
	 * Create a detached, initialised Assignment1Record
	 */
	public Assignment1Record(java.lang.Long eid, java.lang.String ename, java.lang.String doj, java.lang.Long yoe, java.lang.String designation) {
		super(tech.codingclub.helix.tables.Assignment1.ASSIGNMENT1);

		setValue(0, eid);
		setValue(1, ename);
		setValue(2, doj);
		setValue(3, yoe);
		setValue(4, designation);
	}
}
